### PR TITLE
Attempting to fix epafiles redirect

### PR DESCRIPTION
**Pull request by john-moore-levesque**
Original PR was for wrong branch

### CODE REVIEW

**Comment by azinck** [comment]
@john-moore-levesque Since this code does exist in the main branch the work should be started from that branch and PR'd against that branch.  The practice of taking out PRs directly against live is not something we generally want to be doing, and the only reason we do it occasionally right now is because there's infrastructure work that currently does not yet exist in main, but we're working on remedying that.  Do you want me to cherry-pick this over to a new branch based on main, or are you comfortable with doing that?

**Comment by john-moore-levesque** [comment]
@azinck I thought that we were supposed to do PRs against the live branch since that's what gets deployed?

**Comment by azinck** [comment]
@john-moore-levesque Here's the relevant portion from the email I sent out where I tried to explain it: 

> Any time you need to make a code change please base your feature branch on the `main` branch, do your work there, then take out a PR against `main`.  I noticed, for instance, the recent redirect changes were made directly on ci-work which meant that they otherwise wouldn't have ended up in main, which is a problem (don't worry: I went back and cherry-picked the changes into main to rectify the situation).
> 
> One current exception is if you need to make a change to terraform.  The main branch doesn't have the latest terraform in it (Alex is still working on updating our infrastructure to allow us to merge this in), so during this transition period you'll have to base your terraform work on live and take out a PR against live.
> 
> Using PRs and getting another person to look at  your code is certainly a best practice, but if you're willing to accept the risk of directly merging your work to main (or live, if terraform) and you feel it's the appropriate thing to do in the situation then I understand.

Let me know if you have questions.

**Comment by john-moore-levesque** [comment]
@azinck Please confirm that this is what I should do:

1. Close this current PR and branch
2. Create a new feature branch off of "main" and do my work there
3. Create a PR to merge my feature branch into main

Is that correct?

**Comment by azinck** [comment]
@john-moore-levesque Yep, that's perfect!  

In this case you could avoid having to manually do the work again in your new branch by cherry-picking the commit from your old branch onto your new branch: `git cherry-pick 8388be9757363ecc182c7aa153e65089c3c8dcbb`

**Pull request closed without merging**
